// Tests that toy.map is correctly generated by MLIRGen.
// The full affine lowering of map requires fixing FuncOpLowering to handle
// private toy functions (not just main), which is a separate task.
//
// RUN: toyc-ch7 %s -emit=mlir 2>&1 | FileCheck %s

toy.func private @double(%arg0: tensor<*xf64>) -> tensor<*xf64> {
  %0 = toy.add %arg0, %arg0 : tensor<*xf64>
  toy.return %0 : tensor<*xf64>
}

toy.func @main() {
  %0 = toy.constant dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00],
                            [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf64>
  %1 = toy.map @double(%0) : tensor<2x3xf64> -> tensor<2x3xf64>
  toy.print %1 : tensor<2x3xf64>
  toy.return
}

// CHECK: toy.func private @double
// CHECK: toy.func @main
// CHECK:   %[[A:.*]] = toy.constant
// CHECK:   %[[B:.*]] = toy.map @double(%[[A]]) : tensor<2x3xf64> -> tensor<2x3xf64>
// CHECK:   toy.print %[[B]] : tensor<2x3xf64>
